automobile/urls.py
from .views import *
from django.urls import path

app_name = "automobile"
urlpatterns = [
    path('',HomeView.as_view(),name='automobile'),
    path('login/',LOGIN,name='login'),
    path('logout/',logoutUser,name='logout'),
    # path('login/', login_view, name='login_view'),
    path('adminpage/', adminpage, name='adminpage'),
    path('customer/', customer, name='customer'),
    path('staff/', staff, name='staff'),
    # path("",post_list,name="post-list")
    path('Staff/Vechicle/Add',add_update_vechicle,name='add_vechicle'),
    path('Staff/Vechicle/edit/<int:id>/',add_update_vechicle,name='update_vechicle'),
    path('Staff/Vechicle/delete/<int:id>/', delete_vechicle, name='delete_vechicle'),

    path('register/',REGISTER,name='register'),
    # path('delete/<int:id>/', delete_vechicle, name='delete_view'),

]

automobile_website/urls.py
from django.contrib import admin
from django.urls import include, path
from automobile_website import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('automobile.urls',namespace="automobile")),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<!-- Navbar -->
<style>
  .hello-msg{
    font-size: 18px;
    margin-right: 20px;
  }
</style>
<header>
    <!-- Nav Container -->
    <div class="nav container">
      <!-- Menu Icon -->
      <i class='bx bx-menu' id="menu-icon"></i>
      <!-- Logo -->
      <a href="" class="logo">Car<span>Point</span></a>
      <!-- Nav List -->
      <ul class="navbar">
        <li><a href="#home" class="active">Home</a></li>
        <li><a href="#cars">Cars</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#parts">Parts</a></li>
        <li><a href="#blog">Our Blog</a></li>
        
        <li><a href="#">
          {% if user.is_authenticated %}
          <span class="hello-msg">Hello,{{request.user}}</span>
          <li><a href="{% url 'automobile:logout' %}">Logout</a></li>
          {% else %}
          <div class="dropdown">
          <span>User Account</span>
          <div class="dropdown-content">
            <ul>
              <li><a href="{% url 'automobile:login' %}" style="text-decoration: none;">Login</a></li>
              <li><a href="{% url 'automobile:register' %}" style="text-decoration: none;">Registration</a></li>
            </ul>
          </div>
        </div></a></li>
        {% endif %}
        
      </ul>
      <!-- Search Icon -->
      <i class='bx bx-search' id="search-icon"></i>
      <!-- Search Box -->
      <div class="search-box container">
        <input type="search" name="" id="" placeholder="Search here...">
      </div>
    </div>
</header>
  <!-- /Navbar -->

templates/includes/messages.html
{% if messages %}
                        {% for message in messages %}
                           {% if message.tags == 'error' %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                           {{message}}
                           <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <spn aria-hidden="true">&times;</spn>
                           </button>
                        </div>
                        {% endif %}
                        {% endfor %}
                        {% endif %}

                        {% if messages %}
                        {% for message in messages %}
                           {% if message.tags == 'success' %}
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                           {{message}}
                           <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <spn aria-hidden="true">&times;</spn>
                           </button>
                        </div>
                        {% endif %}
                        {% endfor %}
                        {% endif %}
                        
                        {% if messages %}
                        {% for message in messages %}
                           {% if message.tags == 'warning' %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                           {{message}}
                           <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <spn aria-hidden="true">&times;</spn>
                           </button>
                        </div>
                        {% endif %}
                        {% endfor %}
                        {% endif %}