automobile/urls.py
from .views import *
from django.urls import path

app_name = "automobile"
urlpatterns = [
    path('',HomeView.as_view(),name='automobile'),
    path('login/',LOGIN,name='login'),
    path('logout/',logoutUser,name='logout'),
    # path('login/', login_view, name='login_view'),
    path('adminpage/', adminpage, name='adminpage'),
    path('customer/', customer, name='customer'),
    path('staff/', staff, name='staff'),
    # path("",post_list,name="post-list")
    path('Staff/Vechicle/Add',add_update_vechicle,name='add_vechicle'),
    path('Staff/Vechicle/edit/<int:id>/',add_update_vechicle,name='update_vechicle'),
    path('Staff/Vechicle/delete/<int:id>/', delete_vechicle, name='delete_vechicle'),

    path('register/',REGISTER,name='register'),
    # path('delete/<int:id>/', delete_vechicle, name='delete_view'),

]

automobile_website/urls.py
from django.contrib import admin
from django.urls import include, path
from automobile_website import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('automobile.urls',namespace="automobile")),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>admin page</title>
</head>
<body>
    <h1> hello {{ user.username }} your role is admin</h1>
</body>
</html>

templates/adminpage.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <div class="row mt-5 mb-5" style="margin-top: 150px !important">
    <div class="col-md-6">
      <div class="card text-center mb-3">
        <div class="card-header">
          <h5 class="card-title">Add Vechicle</h5>
        </div>
        <div class="card-body">
          <button class="btn btn-success">
            <a href="{% url 'automobile:add_vechicle' %}" style="color: #fff">
              Add Vechicle
            </a>
          </button>
        </div>
      </div>
    </div>
  </div>
  <div class="row mt-5 mb-5">
    <div class="col-md-6">
      <div class="card text-center mb-3">
        <div class="card-header">
          <h5 class="card-title">Total Cars</h5>
        </div>
        <div class="card-body">
          <p class="card-text">{{vechicle_count}}</p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card text-center mb-3">
        <div class="card-header">
          <h5 class="card-title">Total User</h5>
        </div>
        <div class="card-body">
          <p class="card-text">{{user}}</p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="card text-center mb-3">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Manufacturer</th>
            <th scope="col">Model</th>
            <th scope="col">Year</th>
            <th scope="col">Image</th>
            <th scope="col">Price</th>
            <th scope="col">Author</th>
            <th class="text-right">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for i in vechicle_post %}
          <tr>
            <!-- <th scope="row"></th> -->
            <td>{{i.manufacturer.name}}</td>
            <td>{{i.model}}</td>
            <td>{{i.year}}</td>
            <td>{{i.image}}</td>
            <td>{{i.price}}</td>
            <td>{{i.author}}</td>
            <td class="text-right">
              <div class="actions">
                <a href="{% url 'automobile:update_vechicle' id=i.id %}" class="btn btn-sm bg-success-light mr-2">
                  <i class="fas fa-pen"></i>
                </a>
                <a href="{% url 'automobile:delete_vechicle' id=i.id %}" class="btn btn-sm bg-danger-light">
                  <i class="fas fa-trash"></i>
                </a>
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <title>Auto Mobile</title>
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,500;0,600;0,700;1,400&amp;display=swap">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/fontawesome/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/fontawesome/css/all.min.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/style1.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
 </head>
<body>
  {% include 'includes/header.html' %}

{% block content %}
{% endblock %}
<!-- Footer  -->
 <!-- Footer  -->
 <section class="footer">
  <div class="footer-container container">
    <div class="footer-box">
      <a href="" class="logo">Car <span>Point</span></a>
      <div class="social">
        <a href=""><i class="bx bxl-facebook"></i></a>
        <a href=""><i class="bx bxl-twitter"></i></a>
        <a href=""><i class="bx bxl-instagram"></i></a>
        <a href=""><i class="bx bxl-youtube"></i></a>
      </div>
    </div>
    <div class="footer-box">
      <h3>Page</h3>
      <a href="#">Home</a>
      <a href="#">Cars</a>
      <a href="#">Parts</a>
      <a href="#">Sales</a>
    </div>
    <div class="footer-box">
      <h3>Legal</h3>
      <a href="#">Privacy</a>
      <a href="#">Refund Policy</a>
      <a href="#">Cookie Policy</a>
    </div>
    <div class="footer-box">
      <h3>Contact</h3>
      <p>Kathmandu</p>
      <p>Lalitpur</p>
      <p>Bhaktapur</p>
    </div>
  </div>
</section>
<!-- Copyright -->
<div class="copyright">
  <p>@copyright@sangharsha</p>
</div>
<!-- Link to js -->
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'plugins/apexchart/apexcharts.min.js' %}"></script>
    <script src="{% static 'plugins/apexchart/chart-data.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
<script src="{% static 'js/main1.js' %}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Navbar -->
    {% include 'includes/header.html' %}
    
    <!-- Home -->
    <section class="home" id="home">
      <div class="home-text">
        <h1>We Have Everything <br>Your <span>Car</span>Need</h1>
        <p>Lorem ipsum dolor sit amet consectetur<br> adipisicing elit. In iste odit explicabo hic culpa eligendi, labore dolores delectus minus est, eum voluptates molestiae pariatur iure distinctio minima nihil animi? Sint.</p>
        <!-- Home Button -->
        <a href="#" class="btn">Discover Now</a>
      </div>
    </section>
    
    <!-- Cars Section -->
    <section class="cars" id="cars">
      <div class="heading">
        <span>All Cars</span>
        <h2>We havee all types cars</h2>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus saepe aliquid quia illum ipsa ullam! Magnam aliquam ipsum eligendi consectetur, corrupti enim expedita, beatae architecto ducimus aperiam dolore quisquam. Labore?</p>
      </div>
    </section>

    <!-- Cars Container -->
    <div class="cars-container container">
      <!-- Box 1 -->
      {% for post in posts %}
      <div class="box">
        <img src="{{ post.image.url }}" alt="">
        <h2>{{post.model}}</h2>
        <p>{{post.author}}</p>

      </div>
      {% endfor %}
    </div>
    <!-- <div class="vechicle_count">
      <h2>No.Of Vechicles</h2>
      <h3>{{vechicle_count}}</h3>
    </div> -->
    <!-- About -->
    <section class="about container" id="about">
      <div class="about-img">
        <img src="{% static 'img/about.png' %}" alt="">
      </div>
      <div class="about-text">
        <span>About Us</span>
        <h2>Cheap Prices With <br>Quality Cars</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci atque quo fugiat consectetur explicabo similique, vero sapiente corrupti error quis cumque aliquam nam nostrum quam optio ea tempora accusamus veritatis.</p>
        <!-- About Button -->
        <a href="" class="btn">Learn More</a>
      </div>
    </section>

    <!-- Parts Section -->
    <section class="parts" id="parts">
      <div class="heading">
        <span>What We Offer</span>
        <h2>Our Car Is Always Excellence</h2>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem non commodi dignissimos voluptatem nisi quam suscipit facilis necessitatibus. Cupiditate voluptatem et nesciunt veniam impedit excepturi vero a! Saepe, quisquam harum.</p>
      </div>
      <!-- Parts Container -->
      <div class="parts-container container">
        <!-- Box 1 -->
        <div class="box">
          <img src="{% static 'img/part1.png' %}" alt="">
          <h3>Auto Spare Parts</h3>
          <span>Rs 24500</span>
          <i class="bx bxs-star">(6 Reviews)</i>
          <a href="#" class="btn">Buy Now</a>
          <a href="" class="details">View Details</a>
        </div>
        <!-- Box 2 -->
        <div class="box">
          <img src="{% static 'img/part2.png' %}" alt="">
          <h3>Auto Spare Parts</h3>
          <span>Rs 24500</span>
          <i class="bx bxs-star">(6 Reviews)</i>
          <a href="#" class="btn">Buy Now</a>
          <a href="" class="details">View Details</a>
        </div>
        <!-- Box 3 -->
        <div class="box">
          <img src="{% static 'img/part3.png' %}" alt="">
          <h3>Auto Spare Parts</h3>
          <span>Rs 24500</span>
          <i class="bx bxs-star">(6 Reviews)</i>
          <a href="#" class="btn">Buy Now</a>
          <a href="" class="details">View Details</a>
        </div>
        <!-- Box 4 -->
        <div class="box">
          <img src="{% static 'img/part4.png' %}" alt="">
          <h3>Auto Spare Parts</h3>
          <span>Rs 24500</span>
          <i class="bx bxs-star">(6 Reviews)</i>
          <a href="#" class="btn">Buy Now</a>
          <a href="" class="details">View Details</a>
        </div>
        <!-- Box 5 -->
        <div class="box">
          <img src="{% static 'img/part5.png' %}" alt="">
          <h3>Auto Spare Parts</h3>
          <span>Rs 24500</span>
          <i class="bx bxs-star">(6 Reviews)</i>
          <a href="#" class="btn">Buy Now</a>
          <a href="" class="details">View Details</a>
        </div>
        <!-- Box 6 -->
        <div class="box">
          <img src="{% static 'img/part6.png' %}" alt="">
          <h3>Auto Spare Parts</h3>
          <span>Rs 24500</span>
          <i class="bx bxs-star">(6 Reviews)</i>
          <a href="#" class="btn">Buy Now</a>
          <a href="" class="details">View Details</a>
        </div>
      </div>
    </section>

    <!-- Blog Contains -->
    <section class="blog" id="blog">
      <div class="heading">
        <span>Blog & News</span>
        <h2>Our Blog Content</h2>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem non commodi dignissimos voluptatem nisi quam suscipit facilis necessitatibus. Cupiditate voluptatem et nesciunt veniam impedit excepturi vero a! Saepe, quisquam harum.</p>
      </div>
      <!-- Blog Container -->
      <div class="blog-container container">
           <!-- Blog 1 -->
           <div class="box">
             <img src="{% static 'img/car1.jpg' %}" alt="">
             <span>Feb 14 2023</span>
             <h3>How To Get Perfect Car At Low Price</h3>
             <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore aspernatur fuga similique?</p>
             <a href="#" class="blog-btn">Read More <i class="bx bx-right-arrow-alt"></i></a>
           </div>
           <!-- Blog 2 -->
           <div class="box">
             <img src="{% static 'img/car2.jpg' %}" alt="">
             <span>Feb 14 2023</span>
             <h3>How To Get Perfect Car At Low Price</h3>
             <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore aspernatur fuga similique?</p>
             <a href="#" class="blog-btn">Read More <i class="bx bx-right-arrow-alt"></i></a>
           </div>
           <!-- Blog 3 -->
           <div class="box">
             <img src="{% static 'img/car3.jpg' %}" alt="">
             <span>Feb 14 2023</span>
             <h3>How To Get Perfect Car At Low Price</h3>
             <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore aspernatur fuga similique?</p>
             <a href="#" class="blog-btn">Read More <i class="bx bx-right-arrow-alt"></i></a>
           </div>
           <!-- Blog 4 -->
           <div class="box">
             <img src="{% static 'img/car4.jpg' %}" alt="">
             <span>Feb 14 2023</span>
             <h3>How To Get Perfect Car At Low Price</h3>
             <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Labore aspernatur fuga similique?</p>
             <a href="#" class="blog-btn">Read More <i class="bx bx-right-arrow-alt"></i></a>
           </div>
      </div>
    </section>

   {% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Navbar -->
    {% include 'includes/header.html' %}
    
    <!-- /Navbar -->
    <div class="main-wrapper login-body">
      <div class="login-wrapper">
         <div class="container">
            <div class="loginbox">
               
               <div class="login-right">
                  <div class="login-right-wrap">
                     <h1>Login</h1>
                     <p class="account-subtitle">Access to our dashboard</p>
                     <form action="" method="post">
                      {% csrf_token %}
                        <div class="form-group">
                            <input class="form-control" type="text" placeholder="Username" name="username">
                        </div>
                        <div class="form-group">
                           <input class="form-control" type="password" placeholder="Password" name="password">
                        </div>
                        <div class="form-group">
                           <button class="btn btn-primary btn-block" type="submit">Login</button>
                        </div>
                     </form>
                     {% include 'includes/messages.html' %}
                     <div class="text-center forgotpass"><a href="forgot-password.html">Forgot Password?</a></div>
                     <div class="login-or">
                        <span class="or-line"></span>
                        <span class="span-or">or</span>
                     </div>
                     <div class="text-center dont-have">Don’t have an account? <a href="{% url 'automobile:register' %}">Register</a></div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   {% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Navbar -->
    {% include 'includes/header.html' %}
    
    <!-- /Navbar -->
    
    <div class="main-wrapper login-body">
      <div class="login-wrapper">
        <div class="container">
          <div class="loginbox">
            <div class="login-right">
              <div class="login-right-wrap">
                <h1>Register</h1>
                <p class="account-subtitle">Access to our dashboard</p>

                <form
                  action="" method="post"
                >
                {% csrf_token %}
                  <div class="form-group">
                    {{form.username}}
                  </div>
                  <div class="form-group">
                    {{form.email}}
                  </div>
                  <div class="form-group">
                    {{form.password1}}
                  </div>
                  <div class="form-group">
                    {{form.password2}}
                  </div>
                  <!-- <div class="d-flex mb-3 align-items-center">
                    <label class="control control--checkbox mb-0"><span class="caption">SuperUser</span>
                        {{ form.is_superuser }}
                      <div class="control__indicator"></div>
                    </label>
                  </div> -->
                  <div class="d-flex mb-3 align-items-center">
                    <label class="control control--checkbox mb-0"><span class="caption">customer</span>
                        {{ form.is_customer }}
                      <div class="control__indicator"></div>
                    </label>
                  </div>
                  <div class="d-flex mb-3 align-items-center">
                    <label class="control control--checkbox mb-0"><span class="caption">Staff</span>
                        {{ form.is_staff }}
                      <div class="control__indicator"></div>
                    </label>
                  </div>
                  <div class="form-group mb-0">
                    <button class="btn btn-primary btn-block" type="submit" name="create_user">
                      Register
                    </button>
                  </div>
                </form>
                {{form.errors}}
                <div class="login-or">
                  <span class="or-line"></span>
                  <span class="span-or">or</span>
                </div>
                <div class="text-center dont-have">
                  Already have an account? <a href="{% url 'automobile:login' %}">Login</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}

templates/staff.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row mt-5 mb-5" style="margin-top: 150px !important;">

        <div class="col-md-6">
            <div class="card text-center mb-3" >
                <div class="card-header">
                    <h5 class="card-title">Add Vechicle</h5>
                </div>
                <div class="card-body">
                    <button class="btn btn-success">
                        <a href="{% url 'automobile:add_vechicle' %}" style="color: #fff;">
                            Add Vechicle
                        </a>
                    </button>
                </div>
            </div>
        </div>

    </div>
    <div class="row mt-5 mb-5">
        <div class="col-md-6">
            <div class="card text-center mb-3" >
                <div class="card-header">
                    <h5 class="card-title">Total Cars</h5>
                </div>
                <div class="card-body">
                    <p class="card-text">{{vechicle_count}}</p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card text-center mb-3" >
                <div class="card-header">
                    <h5 class="card-title">Total User</h5>
                </div>
                <div class="card-body">
                    <p class="card-text">{{user}}</p>
                </div>
            </div>
        </div> 

    </div>
    <div class="row">
        <div class="card text-center mb-3" >
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Manufacturer</th>
                    <th scope="col">Model</th>
                    <th scope="col">Year</th>
                    <th scope="col">Image</th>
                    <th scope="col">Price</th>
                    <th scope="col">Author</th>
                    <th class="text-right">Action</th>
                  </tr>
                </thead>
                <tbody>
                    {% for i in vechicle_post %}
                  <tr>
                    <!-- <th scope="row"></th> -->
                    <td>{{i.manufacturer.name}}</td>
                    <td>{{i.model}}</td>
                    <td>{{i.year}}</td>
                    <td>{{i.image}}</td>
                    <td>{{i.price}}</td>
                    <td>{{i.author}}</td>
                    <td class="text-right">
                               <div class="actions">
                                  <a href="" class="btn btn-sm bg-success-light mr-2">
                                  <i class="fas fa-pen"></i>
                                  </a>
                                  <a href="" class="btn btn-sm bg-danger-light">
                                  <i class="fas fa-trash"></i>
                                  </a>
                               </div>
                            </td>
                </tr>
                {% endfor %}
                </tbody>
              </table>
        </div>
    </div>
</div>
    
{% endblock %}